administration/urls.py
from django.urls import path
from .views import (AdminView, AddProduct, NewAd, AllOrders, CreateNewSeller,
                    OrderChartView,ProductDetail,ProductListView,
                    DeleteExpiredAds,DeleteProduct,DeleteProductImage,deliver_order)

app_name = 'admn'

urlpatterns = [
    path('', AdminView.as_view(), name='home'),
    path('add-product', AddProduct.as_view(), name='add_product'),
    path('all-orders', AllOrders.as_view(), name='all_orders'),
    path('all-products', ProductListView.as_view(), name='all_products'),
    path('new-ad', NewAd.as_view(), name='new_ad'),
    path('create-seller', CreateNewSeller.as_view(), name='create_seller'),
    path('order-data',OrderChartView.as_view(),name='order_data'),
    path('expired-ads',DeleteExpiredAds.as_view(),name='expired_ads'),
    path('delete-product/<code>',DeleteProduct.as_view(),name='delete_product'),
    path('product-detail/<code>',ProductDetail.as_view(),name='product_detail'),
    path('del-prod-img/<id>',DeleteProductImage.as_view(),name='del_prod_img'),
    path('deliver-order/<id>',deliver_order,name='deliver_order'),

]

ads/urls.py
from django.urls import path
from .views import ad_categories_view,AdDetailCreate,ad_category_detail,create_ad,Ads
app_name = 'ads'

urlpatterns = [
    path('',ad_categories_view,name='index'),
    path('<name>',ad_category_detail,name='ad_cat_detail'),
    path('create_ad/',create_ad,name='ad_create'),
    path('ads/',Ads,name='sponsored_ads'),
    path('create-details/',AdDetailCreate.as_view(),name='ad_details_create')
]

paystack/urls.py
import django

version = django.get_version().split(".")
if int(version[0]) >= 2:
    from django.urls import re_path as url
else:
    from django.conf.urls import url

from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views

urlpatterns = [
    url(
        r"^verify-payment/(?P<order>[\w.@+-]+)/$",
        views.verify_payment,
        name="verify_payment",
    ),
    url(
        r"^failed-verification/(?P<order_id>[\w.@+-]+)/$",
        views.failure_redirect_view,
        name="failed_verification",
    ),
    url(
        r"^successful-verification/(?P<order_id>[\w.@+-]+)/$",
        views.success_redirect_view,
        name="successful_verification",
    ),
    url(
        r"^failed-page/$",
        views.TemplateView.as_view(template_name="paystack/failed-page.html"),
        name="failed_page",
    ),
    url(
        r"^success-page/$",
        views.TemplateView.as_view(template_name="paystack/success-page.html"),
        name="success_page",
    ),
    url(r"^webhook/$", csrf_exempt(views.webhook_view), name="webhook"),
]

products/urls.py
from django.urls import path
from .views import (AddItemToCart,
remove_whole_from_cart,order_final,product_detail,ProductList,
pay_now,add_product_review,ProdCatList,remove_single_item
)


app_name = 'products'

urlpatterns = [
    path('',ProductList.as_view(),name='products'),
    path('product-category/<slug>',ProdCatList.as_view(),name='product_categories'),
    path('add_review',add_product_review,name='add_review'),                                                 #Products
    # path('well',stranger_products,name='stranger'),                                         #products for strangers
    path('<code>/',product_detail,name='detail'),                                  #proposed detail view for products
    path('remove_single/<code>',remove_single_item,name='remove_single'),                         #adding a product to cart
    path('add_to_cart/<code>',AddItemToCart.as_view(),name='add_to_cart'),                         #adding a product to cart
    path('remove_whole_from_cart/<code>',remove_whole_from_cart,name='remove_whole'),       #removing all instances of a product from cart
    path('order_final_summary',order_final,name='order_final'),                             #order summary(cart)
    path('pay_now',pay_now,name='pay_now',)                                                 #pay now
]

administration/models.py
from django.db import models

# Create your models here.

products/models.py
import random
from django.db import models
from django.shortcuts import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.db.models.signals import post_save


def checkExistenceOfCode(code):
    return Product.objects.filter(code=code).exists()


def generate_product_code():
    code = ''
    for x in range(16):
        code += str(random.randrange(9))
    if checkExistenceOfCode(code):
        return generate_product_code()
    return code
# Create your models here.


PRODUCT_CATEGORY = (
    ("PROCESSED_FOOD", "PROCESSED_FOOD"),
    ("CROPS", "CROPS"),
    ("FRUITS", "FRUITS"),
    ("LIVESTOCK", "LIVESTOCK"),
    ("STUDENT_ITEMS", "STUDENT_ITEMS"),
    ("FARM_TOOLS", "FARM_TOOLS"),
    ("FARM_MACHINERY", "FARM_MACHINERY"),
    ("FARM_SERVICES", "FARM_SERVICES"),
    ("FOOD_STUFF", "FOOD_STUFF"),
    ("LAND", "LAND"),
    ("OTHER", "OTHER")
)


# Company Orders(special)
class CompanyOrder(models.Model):
    quality = models.CharField(max_length=100)
    quantity = models.IntegerField(default=0)
    created_date = models.DateTimeField(auto_now_add=True)
    location_of_delivery = models.CharField(max_length=1000)
    total_price = models.FloatField()
    expected_delivery_date = models.DateField()


# Product
class Product(models.Model):
    name = models.CharField(max_length=1000)
    code = models.CharField(max_length=1000, null=True, blank=True)
    price = models.FloatField()
    description = models.TextField()
    category = models.CharField(max_length=40, choices=PRODUCT_CATEGORY)
    is_ad = models.BooleanField(default=False)
    ad_payment_settled = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def detail(self):
        return reverse('products:detail', kwargs={'slug': self.code})

    def get_price(self):
        return self.price

    @property
    def image(self):
        if ProductImage.objects.filter(product=self).exists():
            return ProductImage.objects.filter(product=self).first().image
        return None

    @property
    def images(self):
        if ProductImage.objects.filter(product=self).exists():
            return ProductImage.objects.filter(product=self)


class ProductImage(models.Model):
    image = models.ImageField(upload_to='products')
    product = models.ForeignKey(
        Product, related_name='images', on_delete=models.CASCADE)


# Ordered Products
class OrderedProduct(models.Model):
    item = models.ForeignKey(Product, on_delete=models.CASCADE, null=True,
                             blank=True, related_name='in_cart')  # remember to set null#
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=0)

    def get_normal_total_price(self):
        if self.item is not None:
            return self.item.price * self.quantity
        else:
            return 0

    def get_final_price(self):
        return self.get_normal_total_price()

    def str(self):
        return "{} of {}".format(self.quantity, self.item.name)

# Orders


class Order(models.Model):
    order_items = models.ManyToManyField(OrderedProduct)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    delivered = models.BooleanField(default=False)
    refunded = models.BooleanField(default=False)
    created_time = models.DateTimeField(auto_now_add=True)
    im_reference_code = models.CharField(max_length=20, null=True, blank=True)
    amount_paid = models.CharField(max_length=400, null=True, blank=True)
    ordered = models.BooleanField(default=False)
    paystack_reference_code = models.CharField(
        null=True, blank=True, max_length=100)
    delivery_location = models.CharField(max_length=200, null=True, blank=True)
    time_left = models.IntegerField(default=50)
    pay_on_delivery = models.BooleanField(default=False)

    @property
    def get_amount_paid(self):
        try:
            return float(self.amount_paid[1:])
        except:
            return 0

    def get_total_order_price(self):
        total = 0
        for item in self.order_items.all():
            total += item.get_final_price()
        return total

    @property
    def get_products(self):
        content = ''
        for item in self.order_items.all():
            content += '{}({}), '.format(item.item.name,item.quantity)
        return content

    def str(self):
        return self.user.username

# Address for deliveries


class Address(models.Model):
    address = models.CharField(max_length=200)
    user = models.ForeignKey(
        User, related_name='address', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Addresses'


class ProductReview(models.Model):
    review = models.TextField()
    user = models.CharField(max_length=10)
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='reviews', null=True, blank=True)


def assign_code(sender, instance, created, **kwargs):
    if created:
        instance.code = generate_product_code()
        instance.save()


post_save.connect(assign_code, sender=Product)

administration/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.views.generic import View, ListView,DetailView
from django.contrib import messages
from django.db.models.aggregates import Sum
from django.contrib.auth.models import User
from products.models import PRODUCT_CATEGORY, Product, ProductImage, Order
from ads.models import Seller, Ad, AdCategory
from django.utils import timezone
from .mixins import IsAdminMixin
from django.db.models import Q

MONTHS = {1:'Jan',2:'Feb',3:'Mar',4:'Apr',5:'May',6:'Jun',7:'Jul',8:'Aug',9:'Sep',10:'Oct',11:'Nov',12:'Dec'}

class AdminView(IsAdminMixin, View):
    def get(self, request):
        ads = Ad.objects.filter(ending_date__gte=timezone.now()).prefetch_related('seller','ad_category','product')
        pending_orders_list = Order.objects.filter(ordered=True,delivered=False)
        pending_orders = pending_orders_list.count()
        context = {'pending_orders_list': pending_orders_list,
                   'pending_orders': pending_orders,
                   'ads':ads,'title':'Overview'}
        return render(request, 'administration/index.html', context)


class AllOrders(IsAdminMixin, View):
    def get(self, request):
        orders = Order.objects.all()
        count = orders.count()
        context = {'orders': orders, 'count': count,'title':'All Orders'}
        return render(request, 'administration/orders.html', context)


class AddProduct(IsAdminMixin, View):
    def get(self, request):
        categories = [i[0] for i in PRODUCT_CATEGORY]
        context = {'categories': categories,'title':'Create New Product'}
        return render(request, 'administration/add_product.html', context)

    def post(self, request):
        name = request.POST.get('name')
        price = request.POST.get('price')
        category = request.POST.get('category')
        description = request.POST.get('description')
        images = request.FILES.getlist('images')

        new_product = Product.objects.create(
            name=name, price=float(price), category=category,
            description=description
        )

        for image in images:
            ProductImage.objects.create(image=image, product=new_product)
        messages.success(request, 'New product added successfully')
        return redirect(request.META['HTTP_REFERER'])


class NewAd(IsAdminMixin, View):
    def get(self, request):
        ad_categories = AdCategory.objects.all()
        sellers = Seller.objects.all()
        categories = [i[0] for i in PRODUCT_CATEGORY]
        context = {'categories': ad_categories,'title':'Create New Ad',
                   'sellers': sellers, 'product_categories': categories}
        return render(request, 'administration/new_ad.html', context)

    def post(self, request):
        product_name = request.POST.get('product_name')
        product_price = request.POST.get('product_price')
        ad_category_id = request.POST.get('ad_category')
        prod_category = request.POST.get('prod_category')
        negotiable = request.POST.get('negotiable')
        seller = request.POST.get('seller')
        images = request.FILES.getlist('images')
        description = request.POST.get('description')

        new_product = Product.objects.create(
            name=product_name,
            price=float(product_price),
            description=description,
            category=prod_category,
            is_ad=True,
            ad_payment_settled=True
        )
        for image in images:
            ProductImage.objects.create(image=image, product=new_product)
        Ad.objects.create(
            ad_category=AdCategory.objects.get(id=ad_category_id),
            seller=Seller.objects.get(id=int(seller)),
            negotiable=(negotiable == 'on'),
            product=new_product
        )
        messages.success(request, 'Ad Created Successfully')
        return redirect(request.META('HTTP_REFERER'))


class CreateNewSeller(IsAdminMixin, View):
    def post(self, request):
        brand_name = request.POST.get('brand_name')
        seller_number = request.POST.get('seller_number')
        whatsapp_number = request.POST.get('whatsapp_number')
        location = request.POST.get('location')
        if Seller.objects.filter(brand_name__iexact=brand_name).exists():
            return JsonResponse({'message': 'Seller with this brand_name already exists'}, status=400)
        user = User.objects.create(username=brand_name)
        user.set_password('12345678')
        seller = Seller.objects.create(
            user=user,
            brand_name=brand_name,
            whatsapp_number=whatsapp_number,
            phone_number=seller_number,
            location=location
        )
        return JsonResponse({'brand_name': seller.brand_name, 'id': seller.id}, status=200)


class OrderChartView(IsAdminMixin,View):
    def get(self,request):
        now = timezone.now()
        current_year = now.year
        current_month = now.month

        orders = Order.objects.all()
        paid_orders = orders.filter(ordered=True)
        unpaid_orders = orders.filter(ordered=False)
        paid_orders_dict = {}
        unpaid_orders_dict = {}
        revenue_dict = {}

        for month in range(1,current_month+1):
            revenue = 0
            paid_orders_sum = paid_orders.filter(
                created_time__year=current_year,
                created_time__month=month
                )
            
            for order in paid_orders_sum:
                revenue+=int(order.amount_paid)
            revenue_dict.update({MONTHS[month]:revenue})
            paid_orders_sum = paid_orders_sum.count()
            paid_orders_dict.update({MONTHS[month]:paid_orders_sum})
            unpaid_orders_sum = unpaid_orders.filter(
                created_time__year=current_year,
                created_time__month=month
                ).count()
            unpaid_orders_dict.update({MONTHS[month]:unpaid_orders_sum})



        return JsonResponse({
            'paid':paid_orders_dict,
            'unpaid':unpaid_orders_dict,
            'revenue':revenue_dict
        })

        

class ProductListView(ListView):
    def get_queryset(self):
        q = self.request.GET.get('filter')
        if q:
            if q != '' and q != 'all':
                return Product.objects.filter(Q(name__icontains=q) | Q(category__icontains=q))
            if q == 'all':
                return Product.objects.all().order_by('category')
        return Product.objects.all().order_by('category')
    
    context_object_name = 'products'
    template_name = 'administration/products.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Products'
        return context


class DeleteExpiredAds(View):
    def get(self,request):
        ads = Ad.objects.filter(ending_date__lte=timezone.now())
        context = {'title':'Expired Ads','ads':ads}
        return render(request,'administration/expired_ads.html',context)

    def post(self,request):
        ads = Ad.objects.filter(ending_date__lte=timezone.now())
        for ad in ads:
            ad.product.delete()

        return redirect(request.META['HTTP_REFERER']) 


class DeleteProduct(IsAdminMixin,View):
    def get(self,request,code):
        product = Product.objects.get(code=code)
        name = product.name
        product.delete()
        messages.success(request, f'{name} deleted successfully')
        return redirect(request.META['HTTP_REFERER']) 


class ProductDetail(IsAdminMixin,View):
    def get(self,request,code):
        product = Product.objects.get(code=code)
        context = {
            'title':product.name,
            'product':product
        }
        return render(request,'administration/product_detail.html',context)

    def post(self,request,code):
        product = Product.objects.get(id=request.POST['product_id'])
        images = request.FILES.getlist('images')
        for image in images:
            ProductImage.objects.create(product=product,image=image)
        return redirect(request.META['HTTP_REFERER']) 

class DeleteProductImage(View):
    def get(self,request,id):
        product_image = ProductImage.objects.get(id=id)
        product_image.delete()
        return redirect(request.META['HTTP_REFERER']) 

        
def deliver_order(request,id):
    order = Order.objects.get(id=id)
    order.delivered=True
    order.save()
    return redirect(request.META['HTTP_REFERER']) 

administration/templates/administration/index.html
{% extends "administration/layouts/base.html" %}
{% load humanize %}
{% load static %}
{% block title %} Dashboard {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Pending Deliveries</h4>
        <p class="category"> All pending deliveries ({{pending_orders}})</p>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table tablesorter " id="">
            <thead class=" text-primary">
              <tr>
                <th>
                  Name
                </th>
                <th>
                  Location
                </th>
                <th>
                  Order Time
                </th>
                <th class="text-center">
                  Products
                </th>
                <th class="text-center">
                  Amount Paid
                </th>
                <th>
                  Action
                </th>
              </tr>
            </thead>
            <tbody>
              {% for order in pending_orders_list %}
              <tr>
                <td>
                  {{order.user.get_full_name}}
                </td>
                <td>
                  {{order.delivery_location}}
                </td>
                <td>
                  {{ order.created_time }}
                </td>
                <td class="text-center">
                  {{order.get_products}}
                </td>
                <td class="text-center">
                  &#8358;{{order.amount_paid|floatformat:2|intcomma}}
                </td>
                <td style="position:absolute"> 
                  <div class="dropdown">
                    <button type="button" class="btn btn-link dropdown-toggle btn-icon" data-toggle="dropdown">
                      <i class="tim-icons icon-pencil"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                      <a class="dropdown-item" href="{% url 'admn:deliver_order' order.id %}">
                        Mark as Delivered</a>
                    </div>
                  </div>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="col-12">
    <div class="card card-chart">
      <div class="card-header ">
        <div class="row">
          <div class="col-sm-6 text-left">
            <h5 class="card-category">Total Orders</h5>
            <h2 class="card-title">Orders</h2>
          </div>
          <div class="col-sm-6">
            <div class="btn-group btn-group-toggle float-right" data-toggle="buttons">
              <label class="btn btn-sm btn-primary btn-simple active" id="0">
                <input type="radio" name="options" checked>
                <span class="d-none d-sm-block d-md-block d-lg-block d-xl-block">Paid</span>
                <span class="d-block d-sm-none">
                  <i class="tim-icons icon-single-02"></i>
                </span>
              </label>
              <label class="btn btn-sm btn-primary btn-simple" id="2">
                <input type="radio" class="d-none" name="options">
                <span class="d-none d-sm-block d-md-block d-lg-block d-xl-block">Unpaid</span>
                <span class="d-block d-sm-none">
                  <i class="tim-icons icon-tap-02"></i>
                </span>
              </label>
            </div>
          </div>
        </div>
      </div>
      <!-- chart for orders -->
      <div class="card-body">
        <div class="chart-area">
          <canvas id="chartBig1"></canvas>
        </div>
      </div>
      <!-- end chart for orders -->
    </div>
  </div>

</div>



<!-- revenue -->
<div class="row">

  <div class="col-12">
    <div class="card card-chart">
      <div class="card-header ">
        <div class="row">
          <div class="col-sm-6 text-left">
            <h5 class="card-category">Total Revenue</h5>
            <h2 class="card-title">Revenue</h2>
          </div>
          <div class="col-sm-6">
            <div class="btn-group btn-group-toggle float-right" data-toggle="buttons">
              <!-- <label class="btn btn-sm btn-primary btn-simple active" id="0">
                <input type="radio" name="options" checked>
                <span class="d-none d-sm-block d-md-block d-lg-block d-xl-block">Paid</span>
                <span class="d-block d-sm-none">
                  <i class="tim-icons icon-single-02"></i>
                </span>
              </label>
              <label class="btn btn-sm btn-primary btn-simple" id="2">
                <input type="radio" class="d-none" name="options">
                <span class="d-none d-sm-block d-md-block d-lg-block d-xl-block">Unpaid</span>
                <span class="d-block d-sm-none">
                  <i class="tim-icons icon-tap-02"></i>
                </span>
              </label> -->
            </div>
          </div>
        </div>
      </div>
      <!-- chart for orders -->
      <div class="card-body">
        <div class="chart-area">
          <canvas id="chartBig2"></canvas>
        </div>
      </div>
      <!-- end chart for orders -->
    </div>
  </div>

</div>
<!-- end revenue -->


<div class="row">

  <div class="col-lg-12 col-md-12">
    <div class="card ">
      <div class="card-header">
        <h4 class="card-title">Current Ads</h4>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table tablesorter " id="">
            <thead class=" text-primary">
              <tr>
                <th>
                  Seller
                </th>
                <th>
                  Name
                </th>
                <th>
                  Plan
                </th>
                <th>
                  Expires
                </th>
                <th class="text-center">
                  Fee
                </th>
                <th class="text-center">
                  Views
                </th>
              </tr>
            </thead>
            <tbody>
              {% for ad in ads %}
              <tr>
                <td>
                  {{ad.seller.brand_name}}
                </td>
                <td>
                  {% if ad.product %}
                  <a href="{% url 'products:detail' ad.product.code %}">
                    {{ad.product.name}}</a>
                    {% endif %}
                </td>
                <td>
                  {{ad.ad_category.name}}
                </td>
                <td>
                  {{ad.ending_date}}
                </td>
                <td class="text-center">
                  &#8358;{{ad.ad_category.cost|floatformat:2|intcomma}}
                </td>
                <td class="text-center">
                  {{ad.view}}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script src="{% static 'administration/assets/demo/demo.js' %}"></script>
<script>
  var paidData, unpaidData, revenue;
  let orderDataURL = "{% url 'admn:order_data' %}"
  $(document).ready(function () {
    $.ajax({
      type: 'GET',
      url: orderDataURL,
      success: function (response) {
        paidData = response.paid;
        unpaidData = response.unpaid;
        revenue = response.revenue;
        demo.initDashboardPageCharts();
      },
      error: function (response) {
        alert('E choke')
      }
    })
    // Javascript method's body can be found in assets/js/demos.js

  });
</script>
{% endblock javascripts %}

administration/templates/administration/products.html
{% extends "administration/layouts/base.html" %}
{% load humanize %}
{% block title %} Dashboard {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class='row'>
    <div class="col-md-12">
        <form>
        <input name='filter' type="text" placeholder="Search Products. To see all products again, type all" class="form-control">
        </form>
    </div>
    <br/>
    <br/>
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">All Products</h4>
                <p class="category">({{products.count}})</p>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table tablesorter " id="">
                        <thead class=" text-primary">
                            <tr>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Category
                                </th>
                                <th>
                                    Price
                                </th>
                                <th class="text-center">
                                    Is Ad
                                </th>

                                <th class="text-center">
                                    Created
                                </th>
                                <th>
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product in products %}
                            <tr>
                                <td>
                                    <a href="{% url 'products:detail' product.code %}">
                                        {{product.name}}
                                    </a>
                                </td>
                                <td>
                                    {{product.category}}
                                </td>
                                <td>
                                    &#8358;{{product.price|floatformat:2|intcomma}}
                                </td>
                                <td class="text-center">
                                    {{ product.is_ad }}
                                </td>
                                <td class="text-center">
                                    {{product.created}}
                                </td>
                                <td>
                                <a href="{% url 'admn:delete_product' product.code %}">
                                    <i class="tim-icons icon-trash-simple"></i>
                                </a>
                                &nbsp;
                                <a href="{% url 'admn:product_detail' product.code %}">
                                    <i class="tim-icons icon-pencil"></i>
                                </a>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="6">
                                    <p>No products matched your search query</p>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}