ads/urls.py
from django.urls import path
from .views import ad_categories_view,AdDetailCreate,ad_category_detail,create_ad,Ads
app_name = 'ads'

urlpatterns = [
    path('',ad_categories_view,name='index'),
    path('<name>',ad_category_detail,name='ad_cat_detail'),
    path('create_ad/',create_ad,name='ad_create'),
    path('ads/',Ads,name='sponsored_ads'),
    path('create-details/',AdDetailCreate.as_view(),name='ad_details_create')
]

indus_mega_farms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from .views import homepage,about,ads_txt
# from ads.views import sponsoredAds

urlpatterns = [
      # path('competitions/',include('i_competitions.urls'))                                              #competitions
      path('oginni/', admin.site.urls),                                                               #admin
      path('',homepage,name='home'),     
      path('ads/',include('ads.urls')),                                                                 #homepage
      path('user/',include('users.urls')),                                                            #users
      path('products/',include('products.urls')),                                                     #products
      path('about/',about,name='about'),                                                              #about us
      url(r"^referrals/", include("pinax.referrals.urls", namespace="pinax_referrals")),              #pinax referrals
      url(r"^account/", include("account.urls")),                                                     #django-user-accounts(for pinax to work smoothly)
      path('paystack',include(('paystack.urls','paystack'),namespace='paystack')),                    #paystack
      path('blog/',include('blog.urls')), 
      path('summernote/', include('django_summernote.urls')),    
      path('management/',include('administration.urls')), 
      path('ads.txt',ads_txt,name='google_ads.txt')       
]

if settings.DEBUG:
      urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

paystack/urls.py
import django

version = django.get_version().split(".")
if int(version[0]) >= 2:
    from django.urls import re_path as url
else:
    from django.conf.urls import url

from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views

urlpatterns = [
    url(
        r"^verify-payment/(?P<order>[\w.@+-]+)/$",
        views.verify_payment,
        name="verify_payment",
    ),
    url(
        r"^failed-verification/(?P<order_id>[\w.@+-]+)/$",
        views.failure_redirect_view,
        name="failed_verification",
    ),
    url(
        r"^successful-verification/(?P<order_id>[\w.@+-]+)/$",
        views.success_redirect_view,
        name="successful_verification",
    ),
    url(
        r"^failed-page/$",
        views.TemplateView.as_view(template_name="paystack/failed-page.html"),
        name="failed_page",
    ),
    url(
        r"^success-page/$",
        views.TemplateView.as_view(template_name="paystack/success-page.html"),
        name="success_page",
    ),
    url(r"^webhook/$", csrf_exempt(views.webhook_view), name="webhook"),
]

users/urls.py
from django.urls import path,re_path,reverse_lazy
from django.shortcuts import redirect
from . import views
from django.contrib.auth.views import (LogoutView,LoginView,PasswordResetView,PasswordResetConfirmView,
PasswordResetDoneView,PasswordResetCompleteView,PasswordChangeView)

app_name = 'users'
urlpatterns = [
    path('category/',views.choice,name='category'),
    path('signup/',views.SignupView.as_view(),name='signup'),
    path('login/',LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('user_home/', views.user_home, name='user_home'),
    path('reg/student',views.StudentReg.as_view(),name='student_reg'),
    path('reg/farmer',views.FarmerReg.as_view(),name='farmer_reg'),
    path('reg/company',views.CompanyReg.as_view(),name='company_reg'),
    path('reset_password',PasswordResetView.as_view(subject_template_name='users/subject_template.txt',email_template_name='users/email_template.html',template_name='users/password_reset.html',success_url = 'password_reset_done'),name='password_reset'),
    path('password_reset_done',PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    re_path('password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',success_url=reverse_lazy('users:password_reset_complete'))
    ,name='password_reset_confirm'),
    path('password_reset_complete',PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    path('change_password',PasswordChangeView.as_view(template_name='users/password_change.html',success_url='login'),name='password_change'),
    path('send_complaint',views.complaint_form,name='send_complaint'),
    # path('farmers_subscribe',views.FarmerSubscribeView.as_view(),name='farmers_subscribe'),
    # path('gold-farmer',views.FarmGoldPlanDetailView.as_view(),name='gold_farmer'),
    # path('silver-farmer',views.FarmSilverPlanDetailView.as_view(),name='silver_farmer'),
    # path('premium-farmer',views.FarmPremiumPlanDetailView.as_view(),name='premium_farmer'),
    # path('company_subscribe',views.CompanySellerPlanView.as_view(),name='company_subscribe'),
    path('harvest-time-ready',views.set_harvest_time,name='set_harvest_time'),
    path('harvest-time-not-ready',views.falsify_harvest_time,name='falsify_harvest_time'),
    ]

users/views.py
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView,View
from django.contrib.auth import get_user_model,login,authenticate
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect,reverse,render,Http404


from pinax.referrals.models import Referral
from account.views import SignupView as BaseSignupView
from .models import Student,Farmer,Company,ReferralCode,Message,SpecialMessage,ProfilePictures,CompanySellerPlan,FarmerPlan,IMNews
from .forms import StudentForm,FarmerForm,CompanyForm,SignUpForm,ComplaintForm,CategoryForm,ProfilePicForm
from products.models import Order
from indus_mega_farms.utils import newsletter
from paystack.views import payment_verified

User = get_user_model()


# Dashboard
@login_required()
def user_home(request):
    title = "Dashboard"
    newsletter(request)
    pending_orders = Order.objects.filter(ordered=True,delivered=False,user=request.user).all()
    if pending_orders.exists():
        pending_orders = pending_orders
    messages_ = Message.objects.all().order_by('-created_date')
    news = IMNews.objects.all()
    special_messages = SpecialMessage.objects.filter(user=request.user).order_by('-created_date')
    rank = ReferralCode.objects.all()
    ranks = list(rank)
    user_rank = ReferralCode.objects.filter(user__username=request.user.username)
    position=""
    if user_rank.exists():
        rank = ranks.index(user_rank.first())
        if str(rank)[-1] == "2":position = "nd"
        elif str(rank)[-1]=="1":position="st"
        elif str(rank)[-1]=="3":position="rd"
        else:position="th"
    else:
        rank = ""
    if request.method=='POST':
        pic_form = ProfilePicForm(request.POST,request.FILES)
        if pic_form.is_valid():
            pic = pic_form.cleaned_data.get('pic')
            user_pic,created = ProfilePictures.objects.get_or_create(user=request.user)
            user_pic.profile_pic = pic
            user_pic.save()
            return redirect('users:user_home')
    else:
        pic_form = ProfilePicForm()
    
    context = {"title":title,"pending_orders":pending_orders,'rank':rank,'position':position,'general_messages':messages_,'special_messages':special_messages,'pic_form':pic_form
    ,'news':news}
    farm_qs = Farmer.objects.filter(user=request.user)
    company_qs = Company.objects.filter(user=request.user)
    if farm_qs.exists():
        farmer = farm_qs.first()
        farmer_plan = FarmerPlan.objects.filter(subscribee=farmer)
        if farmer_plan.exists():
            farmer_plan = farmer_plan.first()
            context['has_plan'] = True
            context['customers'] = farmer_plan.customers
            context['plan_type'] = farmer_plan.category
    if company_qs.exists():
        company = company_qs.first()
        company_plan = CompanySellerPlan.objects.filter(subscribee=company)
        if company_plan.exists():
            company_plan = company_plan.first()
            context['has_plan'] = True
            context['customers'] = company_plan.patronages
    return render(request,"users/user_home.html",context=context)


# Signing up
class SignupView(BaseSignupView):
    form_class = SignUpForm
    template_name = 'users/signup.html'

    def generate_username(self, form):
        pass

    def after_signup(self, form):
        super(SignupView, self).after_signup(form)
        action = Referral.record_response(self.request, "USER_SIGNUP")
        if action is not None:
            referral = Referral.objects.get(id=action.referral.id)
            code_inter = ReferralCode.objects.get(code=referral)
            code_inter.referred+=1
            code_inter.save()
        # May need to login user here
        username = form.cleaned_data.get("username")
        password1 = form.cleaned_data.get("password1")
        first_name = form.cleaned_data.get("first_name")
        last_name = form.cleaned_data.get("last_name")
        email = form.cleaned_data.get("email")


        user = authenticate(username=username,password=password1)
        user.first_name = first_name
        user.last_name = last_name
        user.email = email
        user.save()
        SpecialMessage.objects.create(
            user=user,
            title = 'Welcome',
            message = "Welcome to Indus Mega Farms, {}".format(user.username)
        )
        login(self.request,user)
    
        referral = Referral.objects.create(
        user=self.request.user,
        redirect_to=reverse("users:signup")
        )
        referral_code = ReferralCode.objects.create(
            code = referral,
            user = self.request.user
        )
        referral_code.save()

    def create_profile(self, form):
        first_name = form.cleaned_data.get("first_name")
        last_name = form.cleaned_data.get("last_name")
        category = form.cleaned_data.get("category")
        username = form.cleaned_data.get("username")
        password1 = form.cleaned_data.get("password1")

       
# Selecting category
def choice(request):
    title = "Select Category"
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.cleaned_data.get("category")
            if category == "C":
                return redirect("users:company_reg")
            elif category == "F":
                return redirect("users:farmer_reg")
            elif category == "S":
                return redirect("users:student_reg")
        if form.errors:
            messages.info(request,form.errors)
    else:
        form = CategoryForm()
    return render(request,'users/choices.html',{'form':form,"title":title})




# Student details reg
class StudentReg(View):
    def get(self,*args, **kwargs):
        title = "Register as a Student"
        form = StudentForm()
        return render(self.request,'users/student_form.html',{'form':form,"title":title})
    
    def post(self,*args, **kwargs):
        form = StudentForm(self.request.POST or None)
        if form.is_valid():
            phone_number = form.cleaned_data.get('phone_number')
            location = form.cleaned_data.get('location')
            student = Student.objects.create(
                phone_number = phone_number,
                location=location,
                user = self.request.user,
            )
            student.save()
            messages.success(self.request,'Successfully registered')
            return redirect('users:user_home')
            
        else:
            messages.warning(self.request,'Form not valid')
            return redirect('users:student_reg')
        
# Farmer's detail reg
class FarmerReg(View):
    def get(self,*args, **kwargs):
        form = FarmerForm()
        title = "Register as a Farmer"
        return render(self.request,'users/farmer_form.html',{'form':form,"title":title})
    
    def post(self,*args, **kwargs):
        form = FarmerForm(self.request.POST or None)
        if form.is_valid():
            phone_number = form.cleaned_data.get('phone_number')
            location = form.cleaned_data.get('location')
            farm_name = form.cleaned_data.get('farm_name')
            land_size = form.cleaned_data.get('land_size')
            major_products = form.cleaned_data.get('major_products')
            other_products = form.cleaned_data.get('other_products')
            does_livestock = form.cleaned_data.get('does_livestock')
            farmer = Farmer.objects.create(
                user = self.request.user,
                land_size = land_size,
                location = location,
                farm_name = farm_name,
                major_products = major_products,
                other_products = other_products,
                does_livestock = does_livestock,
                phone_number = phone_number,
            )
            farmer.save()
            messages.success(self.request,'Successfully registered')            
        else:
            messages.warning(self.request,'Form not valid')
        return redirect('users:user_home')



# Company's detail reg
class CompanyReg(View):
    def get(self,*args, **kwargs):
        form = CompanyForm()
        title="Register as a Company"
        return render(self.request,'users/company_form.html',{'form':form,"title":title})
    
    def post(self,*args, **kwargs):
        form = CompanyForm(self.request.POST or None)
        if form.is_valid():
            phone_number = form.cleaned_data.get('phone_number')
            location = form.cleaned_data.get('location')
            company_name = form.cleaned_data.get('company_name')
           
            company = Company.objects.create(
                user = self.request.user,
                phone_number = phone_number,
                location = location,
                company_name = company_name
            )
            company.save()
            messages.success(self.request,'Successfully registered')            
        else:
            messages.warning(self.request,'Form not valid')
        return redirect('users:user_home')




# Complaint form reg
@login_required
def complaint_form(request):
    title = 'Make a Complaint'
    if request.method == 'POST':
        form = ComplaintForm(request.POST)
        if form.is_valid():
            complaint = form.save(commit=False)
            complaint.user=request.user
            complaint.save()
            messages.info(request,"Your complaint will be reviewed shortly.Thank you")
            return redirect("users:user_home")
        else:
            messages.info(request,"Your form is not valid")
    else:
        form = ComplaintForm()
    context = {"title":title,"form":form}
    return render(request,"users/send_complaint.html",context)



   

# set harvest time
@login_required 
def set_harvest_time(request):
    farmer = Farmer.objects.get(user=request.user)
    if not farmer:
        return Http404

users/templates/users/company_form.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block content %}
<div class="container jumbotron">
    <h1  style="color: green;">Company Details</h1>
<form method="POST" class="in_form">
    {% csrf_token %}
{{form.as_p}}
<br>
<input type="submit" value="Submit" class="input-submit">
</form>
</div>
<style>
        .in_form{
            width:60vw;
        }
        </style>
{% endblock %}

users/templates/users/create_advert.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Create an Advert{% endblock %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/unbootstrap.css' %}">
{% endblock css %}

{% block content %}
<div class="container">
<h3>Create your Advert</h3>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="Submit Advert">
</form>
</div>

<style>
.container{display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;}
h3{font-weight: 450;}
</style>
{% endblock %}

{% block footer %}
{% endblock footer%}

users/templates/users/email_template.html
    Click the link below to reset your password
    {{protocol}}://{{domain}}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    If clicking the link doesn't work, try copying and pasting the link in a new browser window
    The Indus-Mega Farms Tech Team.

users/templates/users/farmers_subscribe.html
{% extends 'base.html' %}
{% load static %}
{% load paystack %}
{% block title %}Susbscribe{% endblock title %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/farmers_sub.css' %}">
{% endblock css %}
{% block content %}
    <div class="subscription_container">
           <center> <h1 class="title">Subscription Plans<span></span></h1></center>

        <div class="plans">
            
            <div class="plan premium">
                <h1>Premium</h1>
                <h2>&#8358;100.00</h2>
                <div class="features">
                    <p>2-10 customers max in 90 days</p>
                </div>
                <a href="{% url 'users:premium_farmer' %}" class="cta premium_btn">Choose</a>
            </div>
            
            <div class="plan gold">
                <h1>Gold</h1>
                <h2>&#8358;500.00       </h2>
                <div class="features">
                    <p>50 customers max in 90 days</p>
                    <p>10 customers min in 90 days</p>
                    <p>Higher Recognition compared to silver plan</p>
                </div>

                <a href="{% url 'users:gold_farmer' %}" class="cta gold_btn">Choose</a>

                       
                
            </div>
            
            
         <div class="plan silver">
            <h1>Silver</h1>
            <h2>&#8358;250.00</h2>
            <div class="features">
                <p>5-25 customers max in 90 days</p>
                <p>Higher recognition compared to premium plan</p>
            </div>
                <a href="{% url 'users:silver_farmer' %}" class="cta silver_btn">Choose</a>

            </a>
        </div>
            
        </div>

        <style>
         button{
        background:none;
        outline:none;
    }
    .plan{margin:auto;}
        </style>

{% endblock content %}
{% block footer %}{% endblock footer %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}
{% block content %}

<div class="login_wrapper">
    <h1 class="thin major_header">Log in</h1>
    <form method="post">
        {% csrf_token %}
        {%if form.errors %}
        <div class="errors">
            <p>Wrong Credentials</p>
        </div>
        {% endif %}
        {{form.as_p}}
        <input type="checkbox" onclick="see()" name="" id="seer">
        <input type="submit" class="input-submit" value="Log In">        
    </form>
    <hr>

    <a href="{% url 'users:password_reset' %}" style="color:rgb(69, 182, 69);display:block;">Forgot Password?</a>
    <a href="{% url 'users:signup' %}" style="color:rgb(69, 182, 69);display: block;">Don't have an account?</a>
</div>

<script>
        var opener = document.getElementById("seer");
        function see(){
            var x = document.getElementById("id_password");
            if (x.type==='password'){
                x.type="text";
                
            }
        
            else{
                x.type="password";
            }
        }
        
        var get = document.getElementById("password");
        
        </script>
{% endblock %}
{% block mobile_entry %}

<a href="{% url 'users:signup' %}" class="mobile_entry">Sign up</a>
{% endblock mobile_entry %}

users/templates/users/password_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/unbootstrap.css' %}">
{% endblock css %}

{% block content %}
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}<br>
        <input type="submit" value="Submit" class="btn btn-success">
    </form>
</div>
{% endblock %}

{% block footer %}
{% endblock footer %}

users/templates/users/password_reset.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block content %}
<div class="container">
<h3 class="thin">Password Reset</h3>
<small>Enter your email address in the form below</small>
<hr>
<br>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit" class="input-submit">
</form>
</div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/unbootstrap.css' %}">
{% if validlink %}
<div class="container">
<h3>Reset Password</h3>
<form action="" method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-small btn-success">Reset Password</button>
</form>
</div>
{% else %}
<p>The password reset link was invalid.</p>
{% endif %}
<style>
.container{display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;}
h3{font-weight: 450;}
</style>
{% endblock content %}
{% block footer %}
{% endblock footer %}

users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/unbootstrap.css' %}">
<div class="container">
<h4 class="lead">Please check your email for your password reset link</h4>
<p>If you have an email registered with Indus-Mega Farms, then you should receive a mail with your new login credentials.</p>
</div>
{% endblock %}
{% block footer %}
{% endblock footer %}

users/templates/users/premium.html
{% extends 'base.html' %}
{% load static %}
{% load paystack %}
{% block title %}Susbscribe{% endblock title %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/farmers_sub.css' %}">
{% endblock css %}
{% block content %}
    <div class="subscription_container">
           <center> <h1 class="title">Premium Plan<span></span></h1></center>

        <div class="plans">
            <div class="plan premium">
                <h1>Premium</h1>
                <h2>&#8358;100.00</h2>
                <div class="features">
                    <p>2-10 customers max in 90 days</p>
                </div>
        {% paystack_button amount=amount email=email button_class=" cta silver_btn" %}
    </div>
        </div>
        <style>
            form{
    margin-top:auto;
}
            button{
   margin-top:auto;
            border:none;
           background:none;
           outline:none;
           cursor: pointer;
       }
       .plan{margin:auto;}
           </style>
{% endblock content %}
{% block footer %}{% endblock footer %}

users/templates/users/send_complaint.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Log A Complaint{% endblock %}
{% block css %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/unbootstrap.css' %}">
{% endblock css %}
{% block content %}
<div class="container">
<h3>Send your complaint</h3>
<form action="" method="post">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="Submit Complaint">
</form>
</div>

<style>
.container{display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;}
h3{font-weight: 450;}

</style>
{% endblock %}
{% block footer %}
{% endblock footer %}

users/templates/users/silver.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Silver Plan{% endblock %}
{% load paystack %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/farmers_sub.css' %}">
{% endblock css %}
{% block content %}
<div class="subscription_container">
    <center> <h1 class="title">Silver Plan<span></span></h1></center>
    <div class="plan silver">
        <h1>Silver</h1>
        <h2>&#8358;250.00</h2>
        <div class="features">
            <p>5-25 customers max in 90 days</p>
            <p>Refundable(half payment)</p>
            <p>Higher recognition compared to premium plan</p>
        </div>
        {% paystack_button amount=amount email=email button_class=" cta silver_btn" %}
    </div>
</div>

<style>
    form{
    margin-top:auto;
}
    button{
  border:none;
   background:none;
   outline:none;
   cursor: pointer;
   margin-top:auto;
}
.plan{margin:auto;}
   </style>

{% endblock content %}
{% block footer %}{% endblock footer %}

users/templates/users/student_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Student{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block content %}
<div class="container jumbotron">
    <h1  style="color: green;">Student Details</h1>
<form method="POST" class="in_form">
    {% csrf_token %}
{{form.as_p}}
<br>
<input type="submit" value="Submit" class="input-submit">
</form>
</div>
<style>
.in_form{
    width:60vw;
}
</style>
{% endblock %}