ads/urls.py
from django.urls import path
from .views import ad_categories_view,AdDetailCreate,ad_category_detail,create_ad,Ads
app_name = 'ads'

urlpatterns = [
    path('',ad_categories_view,name='index'),
    path('<name>',ad_category_detail,name='ad_cat_detail'),
    path('create_ad/',create_ad,name='ad_create'),
    path('ads/',Ads,name='sponsored_ads'),
    path('create-details/',AdDetailCreate.as_view(),name='ad_details_create')
]

indus_mega_farms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from .views import homepage,about,ads_txt
# from ads.views import sponsoredAds

urlpatterns = [
      # path('competitions/',include('i_competitions.urls'))                                              #competitions
      path('oginni/', admin.site.urls),                                                               #admin
      path('',homepage,name='home'),     
      path('ads/',include('ads.urls')),                                                                 #homepage
      path('user/',include('users.urls')),                                                            #users
      path('products/',include('products.urls')),                                                     #products
      path('about/',about,name='about'),                                                              #about us
      url(r"^referrals/", include("pinax.referrals.urls", namespace="pinax_referrals")),              #pinax referrals
      url(r"^account/", include("account.urls")),                                                     #django-user-accounts(for pinax to work smoothly)
      path('paystack',include(('paystack.urls','paystack'),namespace='paystack')),                    #paystack
      path('blog/',include('blog.urls')), 
      path('summernote/', include('django_summernote.urls')),    
      path('management/',include('administration.urls')), 
      path('ads.txt',ads_txt,name='google_ads.txt')       
]

if settings.DEBUG:
      urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

paystack/urls.py
import django

version = django.get_version().split(".")
if int(version[0]) >= 2:
    from django.urls import re_path as url
else:
    from django.conf.urls import url

from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views

urlpatterns = [
    url(
        r"^verify-payment/(?P<order>[\w.@+-]+)/$",
        views.verify_payment,
        name="verify_payment",
    ),
    url(
        r"^failed-verification/(?P<order_id>[\w.@+-]+)/$",
        views.failure_redirect_view,
        name="failed_verification",
    ),
    url(
        r"^successful-verification/(?P<order_id>[\w.@+-]+)/$",
        views.success_redirect_view,
        name="successful_verification",
    ),
    url(
        r"^failed-page/$",
        views.TemplateView.as_view(template_name="paystack/failed-page.html"),
        name="failed_page",
    ),
    url(
        r"^success-page/$",
        views.TemplateView.as_view(template_name="paystack/success-page.html"),
        name="success_page",
    ),
    url(r"^webhook/$", csrf_exempt(views.webhook_view), name="webhook"),
]

products/urls.py
from django.urls import path
from .views import (AddItemToCart,
remove_whole_from_cart,order_final,product_detail,ProductList,
pay_now,add_product_review,ProdCatList,remove_single_item
)


app_name = 'products'

urlpatterns = [
    path('',ProductList.as_view(),name='products'),
    path('product-category/<slug>',ProdCatList.as_view(),name='product_categories'),
    path('add_review',add_product_review,name='add_review'),                                                 #Products
    # path('well',stranger_products,name='stranger'),                                         #products for strangers
    path('<code>/',product_detail,name='detail'),                                  #proposed detail view for products
    path('remove_single/<code>',remove_single_item,name='remove_single'),                         #adding a product to cart
    path('add_to_cart/<code>',AddItemToCart.as_view(),name='add_to_cart'),                         #adding a product to cart
    path('remove_whole_from_cart/<code>',remove_whole_from_cart,name='remove_whole'),       #removing all instances of a product from cart
    path('order_final_summary',order_final,name='order_final'),                             #order summary(cart)
    path('pay_now',pay_now,name='pay_now',)                                                 #pay now
]

ads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.utils.text import slugify
from django.utils import timezone
from products.models import Product
from django.conf import settings

#ad category
class AdCategory(models.Model):
    name = models.CharField(max_length=20)
    validity = models.CharField(max_length=10)
    no_of_ads = models.IntegerField()
    cost = models.FloatField()
    image = models.ImageField(upload_to='ad_categories',blank=True,null=True)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True)

    class Meta:
        verbose_name_plural = 'Ad Categories'
    
    def __str__(self):
        return self.name

# class Ad(models.Model):
    
    """Ad"""
class Ad(models.Model):
    ad_category = models.ForeignKey(AdCategory,related_name='ad_category',on_delete=models.SET_NULL,null=True)
    seller = models.ForeignKey('Seller',on_delete=models.CASCADE,related_name='seller_ads',null=True)
    negotiable = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    ending_date = models.DateTimeField(null=True,blank=True)
    product = models.ForeignKey(Product,blank=True,null=True,on_delete=models.CASCADE,related_name='prod_ad')
    view = models.IntegerField(default = 0)
    exhausted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.product:
            return self.product.name
        return str(self.id)

    @property
    def sample(self):
        return self.product.image


class AdDetails(models.Model):
    ad = models.ForeignKey(Ad,on_delete=models.CASCADE,related_name='details')
    label = models.CharField(max_length=20)
    value = models.CharField(max_length=20)

    def __str__(self):
        return self.label + ' : '+self.value
        
def set_ending_date(sender, instance, created, **kwargs):
    if created:
        duration = instance.ad_category.validity
        instance.ending_date = timezone.now() + timezone.timedelta(days=int(duration))
        instance.save()
post_save.connect(set_ending_date,sender=Ad)





# Seller account
class Seller(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,related_name='seller',on_delete=models.CASCADE)
    brand_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    whatsapp_number = models.CharField(max_length=20)
    location = models.CharField(max_length=1000)

    def __str__(self):
        return self.user.username

ads/forms.py
from .models import Seller
from django import forms

class SellerForm(forms.ModelForm):
    class Meta:
        model = Seller
        fields = ['brand_name','phone_number','whatsapp_number','location']

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['phone_number'].widget = forms.TextInput(attrs={'placeholder':'+234...'})
        self.fields['whatsapp_number'].widget = forms.TextInput(attrs={'placeholder':'+234...'})

ads/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect,get_object_or_404
from .models import AdCategory,Seller,Ad,AdDetails
from .forms import SellerForm
from products.models import Product,ProductImage
from django.views.generic import ListView,View
from django.core.paginator import Paginator
from django.template.loader import render_to_string
from django.http import JsonResponse
from utils.functions import generate_product_code
from django.conf import settings



# View for all the ad_categories
def ad_categories_view(request):
    ad_categories = AdCategory.objects.exclude(name='infinite')
    context = {
        'title':'Ads',
        'ad_categories':ad_categories,
    }
    return render(request,'ads/index.html',context)

@login_required
def ad_category_detail(request,name):
    request.session['ad_category'] = name
    login_redirect_url = 'users:login'
    form = SellerForm()
    seller_query = Seller.objects.filter(user=request.user)
    if seller_query.exists():
        is_seller = True
    else:
        is_seller = False
    ad_category = get_object_or_404(AdCategory,name=name)
    is_not_free = True
    if (name=='FREE'):
        is_not_free = False
    context = {
        'title':ad_category.name,
        'ad_category':ad_category,
        'is_seller':is_seller,
        'amount':str(int(ad_category.cost)),
        'email':request.user.email,
        'is_not_free':is_not_free
    }
    if Seller.objects.filter(user=request.user).exists():
        user_ads_items = Ad.objects.filter(ad_category=ad_category,seller=request.user.seller,paid=True)
        all_user_ads = Ad.objects.filter(ad_category=ad_category,seller=request.user.seller)
        context['all_user_ads'] = all_user_ads
        if user_ads_items.exists() or ad_category.name == 'Free Plan' :
            unpaid = False
            context['unpaid'] = False
        else:
            context['unpaid']  = True
            unpaid = True
    if request.method == 'POST':
        if 'details_to_start' in request.POST:
            print(request.POST)
            if not request.POST.get('phone_number').startswith('+'):
                messages.error(request,'Phone number must start with country code')
                return redirect(request.META['HTTP_REFERER'])
                
            if not request.POST.get('whatsapp_number').startswith('+'):
                messages.error(request,'Whatsapp number must start with country code')
                return redirect(request.META['HTTP_REFERER'])
            else:
                form = SellerForm(request.POST)
                if form.is_valid():
                    seller_form = form.save(commit=False)
                    seller_form.user = request.user
                    if is_seller:
                        messages.info(request,'You already have your seller info registered.')
                        return redirect(request.META['HTTP_REFERER'])
                    seller_form.save()
                    messages.info(request,'Seller info registered.')
                    return redirect(request.META['HTTP_REFERER'])
                else:
                    messages.info(request,'Error filling form.')
                    return redirect(request.META['HTTP_REFERER'])

    # if request.user in ad_category.users.all():
    try:
        user_ads = Ad.objects.filter(ad_category=ad_category,seller=request.user.seller)
        context['user_ads'] = user_ads[0]
        if user_ads.exists():
            context['category_user_ads_count'] = user_ads.count
    except:
        context['category_user_ads_count'] = 0

    context["form"] = form
    return render(request,'ads/detail.html',context)


def create_ad(request):
    if request.method == 'POST':
        product_category = request.POST.get('product_category')
        ad_category = request.POST.get('ad_category')
        product_name = request.POST.get('product_name')
        negotiable = request.POST.get('negotiable')
        fixed_price = request.POST.get('fixed_price')
        price = request.POST.get('price')
        images = request.FILES.getlist('product_images')
        description = request.POST.get('description')
        negotiable = (negotiable == 'on')
        new_product = Product.objects.create(
            name=product_name,
            price = price,
            description = description,
            category = product_category,
            is_ad = True
            )
        for image in images:
            ProductImage.objects.create(image=image,product=new_product)
        Ad.objects.create(
            ad_category = AdCategory.objects.get(name=ad_category),
            seller = request.user.seller,
            negotiable = negotiable,
            product = new_product
            )
        return redirect(request.META.get('HTTP_REFERER'))


def Ads(request):
    # paginator = Paginator(sup_ads, 25) # Show 25 contacts per page.
    # page_number = request.GET.get('page')
    # page_obj = paginator.get_page(page_number)
    parameter = request.GET.get("q")
    context = {
        # 'page_obj':page_obj,
        'title':'Indus-Mega Farms',
        'ADS_URL':settings.ADS_URL
    }
    failed = ''
    if parameter:
        if parameter != '':
            results = Product.objects.filter(name__icontains=parameter)
            if not results.exists():
                failed = "No products match your search."
        else:
            results = ''
        if request.is_ajax():
            html = render_to_string(
                template_name="ads/search_results.html", 
                context={"results": results,"failed":failed}
            )

            data_dict = {"html_from_view": html}

        return JsonResponse(data=data_dict, safe=False)

    return render(request,'ads/ads.html',context)
    


class AdDetailCreate(View):
    def post(self,request):
        ad_id = request.POST.get('ad_id')
        ad = Ad.objects.get(id=int(ad_id))
        labels = []
        values = []
        for i in request.POST:
            if i.startswith('label'):
                labels.append(request.POST[i])
            if i.startswith('value'):
                values.append(request.POST[i])
        for (label,value) in zip(labels,values):
            AdDetails.objects.create(ad=ad,label=label,value=value)
                


        return JsonResponse({},status=200)

ads/templates/ads/ads.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}{{title}}{% endblock title%}
{% block css %}
<link rel="stylesheet" href="{% static 'css/ads_presets.css' %}">
<link rel="stylesheet" href="{% static 'css/sponsoredads.css' %}">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
{% endblock css%}
{% block content %}
<section class="ads_section flex_col a-cent j-cent">
    <div>
        <p class="hero_text">Find Products from top selling brands</p>
    </div>
    <div class="search_bar flex">
        <input type="text" name="search" id="user-input" placeholder="Search For Products Here..">
        <div class="search_icon_cover flex a-cent j_cent">
            <svg xmlns="http://www.w3.org/2000/svg" width="35.997" height="36.004" viewBox="0 0 35.997 36.004"
                id="search-icon">
                <path id="Icon_awesome-search" data-name="Icon awesome-search"
                    d="M35.508,31.127l-7.01-7.01a1.686,1.686,0,0,0-1.2-.492H26.156a14.618,14.618,0,1,0-2.531,2.531V27.3a1.686,1.686,0,0,0,.492,1.2l7.01,7.01a1.681,1.681,0,0,0,2.384,0l1.99-1.99a1.7,1.7,0,0,0,.007-2.391Zm-20.883-7.5a9,9,0,1,1,9-9A8.995,8.995,0,0,1,14.625,23.625Z"
                    fill="#fff" />
            </svg>
        </div>
        <div class="fresh">
            {% include 'ads/search_results.html' %}
        </div>
    </div>
</section>
<section class="ad_categories grid">
    <a href="{% url 'products:product_categories' slug='PROCESSED_FOOD' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'svgs/icecream_ct.svg' %}" alt="">
            </div>
            <div class="category_name">Processed Foods</div>
        </div>
    </a>
    <a href="{% url 'products:product_categories' slug='CROPS' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'svgs/crops_ct.svg' %}" alt="">
            </div>
            <div class="category_name">Crops</div>
        </div>
    </a>
    <a href="{% url 'products:product_categories' slug='FARM_MACHINERY' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'svgs/tractor_ct.svg' %}" alt="">
            </div>
            <div class="category_name">Farm Machinery</div>
        </div>
    </a>

    <a href="{% url 'products:product_categories' slug='FARM_SERVICES' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'svgs/services_ct.svg' %}" alt="">
            </div>
            <div class="category_name">Farm Services</div>
        </div>
    </a>

    <a href="{% url 'products:product_categories' slug='FOOD_STUFF' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'svgs/food_ct.svg' %}" alt="">
            </div>
            <div class="category_name">Food Stuff</div>
        </div>
    </a>

    <a href="{% url 'products:product_categories' slug='LAND' %}">

        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'svgs/farm_ct.svg' %}" alt="">
            </div>
            <div class="category_name">Lands</div>
        </div>
    </a>

    <a href="{% url 'products:product_categories' slug='LIVESTOCK' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'svgs/cow_ct.svg' %}" alt="">
            </div>
            <div class="category_name">Livestock</div>
        </div>
    </a>
    <a href="{% url 'products:product_categories' slug='FRUITS' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'svgs/fruit_ct.svg' %}" alt="">
            </div>
            <div class="category_name">Fruits</div>
        </div>
    </a>
    <a href="{% url 'products:product_categories' slug='OTHER' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'images/others.png' %}" alt="" style="height:50px;">
            </div>
            <div class="category_name">Others</div>
        </div>
    </a>

    <a href="{% url 'ads:index' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image category_plus flex a-cent j_cent">
                <span class="add_post"></span>
            </div>
            <div class="category_name">Post an Ad</div>
        </div>
    </a>
</section>
{% comment %}
<section class="popular_ads">
    <h1>Popular Ads</h1>
    <div class="ads grid">
        {% for ad in sup_ads %}
        <a href="{% url 'products:detail' ad.product.slug %}">
            <div class="ad">
                <div class="image" style="background: none;">
                    <img src="{{ad.image.url}}" alt="" style="height:100%;width:100%;object-fit:cover;">
                </div>
                <div class="ad_dets flex_col" style="color:#000">
                    <p>{{ad.name}}</p>
                    <p class="flex sep">&#8358;{{ad.maximum_price|floatformat:2|intcomma}}
                        <span class="small flex a-cent">
                            <img src="svgs/Icon awesome-angle-left.svg" alt="">

                        </span>
                    </p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</section>
{% endcomment %}
{% comment %}
<div class="pagination flex a_cent j_cent" style="margin-top:2rem">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endcomment %}
<script>
    const user_input = $("#user-input")
    const search_icon = $('#search-icon')
    const artists_div = $('.fresh')
    const endpoint = '{{ADS_URL}}'
    const delay_by_in_ms = 700
    let scheduled_function = false

    let ajax_call = function (endpoint, request_parameters) {
        $.getJSON(endpoint, request_parameters)
            .done(response => {
                // fade out the artists_div, then:
                artists_div.fadeTo('slow', 0).promise().then(() => {
                    // replace the HTML contents
                    artists_div.html(response['html_from_view'])
                    // fade-in the div with new contents
                    artists_div.fadeTo('slow', 1)
                    // stop animating search icon
                    search_icon.removeClass('blink')
                })
            })
    }


    user_input.on('keyup', function () {
        if ($(this).val() != '') {
            const request_parameters = {
                q: $(this).val() // value of user_input: the HTML element with ID user-input
            }

            // start animating the search icon with the CSS class
            search_icon.addClass('blink')

            // if scheduled_function is NOT false, cancel the execution of the function
            if (scheduled_function) {
                clearTimeout(scheduled_function)
            }

            // setTimeout returns the ID of the function to be executed
            scheduled_function = setTimeout(ajax_call, delay_by_in_ms, endpoint, request_parameters)
        }
    })

</script>
<script>
    document.querySelector('#user-input').addEventListener('keyup', () => {
        if (document.querySelector('#user-input').value == '') {
            document.querySelector('.results').style.display = 'none'
        }
    })
</script>
<script src="{% static 'js/popads.js' %}"></script>
<style>
    .ad_categories>a {
        color: #000;
    }

    body,
    html {
        height: 100%;
    }

    .fresh {
        position: absolute;
        width: 100%;
        left: 0;
        bottom: -2px;
    }

    .search_bar {
        position: relative;
    }
</style>
{% endblock content %}
{% block js %}
{% endblock js %}

ads/templates/ads/sponsoredad.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}{{title}}{% endblock title%}
{% block css %}
<link rel="stylesheet" href="{% static 'css/ads_presets.css' %}">
<link rel="stylesheet" href="{% static 'css/sponsoredads.css' %}">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
{% endblock css%}
{% block content %}
<section class="ads_section flex_col a-cent j-cent">
    <div>
        <p class="hero_text">Find Products from top selling brands</p>
    </div>
    <div class="search_bar flex">
        <input type="text" name="search" id="user-input" placeholder="Search For Products Here..">
        <div class="search_icon_cover flex a-cent j_cent">
            <svg xmlns="http://www.w3.org/2000/svg" width="35.997" height="36.004" viewBox="0 0 35.997 36.004"
                id="search-icon">
                <path id="Icon_awesome-search" data-name="Icon awesome-search"
                    d="M35.508,31.127l-7.01-7.01a1.686,1.686,0,0,0-1.2-.492H26.156a14.618,14.618,0,1,0-2.531,2.531V27.3a1.686,1.686,0,0,0,.492,1.2l7.01,7.01a1.681,1.681,0,0,0,2.384,0l1.99-1.99a1.7,1.7,0,0,0,.007-2.391Zm-20.883-7.5a9,9,0,1,1,9-9A8.995,8.995,0,0,1,14.625,23.625Z"
                    fill="#fff" />
            </svg>
        </div>
        <div class="fresh">
            {% include 'ads/search_results.html' %}
        </div>
    </div>
</section>
<section class="ad_categories grid">
    <a href="{% url 'products:product_categories' slug='PROCESSED_FOOD' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'svgs/icecream_ct.svg' %}" alt="">
            </div>
            <div class="category_name">Processed Foods</div>
        </div>
    </a>
    <a href="{% url 'products:product_categories' slug='CROPS' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'svgs/crops_ct.svg' %}" alt="">
            </div>
            <div class="category_name">Crops</div>
        </div>
    </a>
    <a href="{% url 'products:product_categories' slug='FARM_MACHINERY' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'svgs/tractor_ct.svg' %}" alt="">
            </div>
            <div class="category_name">Farm Machinery</div>
        </div>
    </a>

    <a href="{% url 'products:product_categories' slug='FARM_SERVICES' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'svgs/services_ct.svg' %}" alt="">
            </div>
            <div class="category_name">Farm Services</div>
        </div>
    </a>

    <a href="{% url 'products:product_categories' slug='FOOD_STUFF' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'svgs/food_ct.svg' %}" alt="">
            </div>
            <div class="category_name">Food Stuff</div>
        </div>
    </a>

    <a href="{% url 'products:product_categories' slug='LAND' %}">

        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'svgs/farm_ct.svg' %}" alt="">
            </div>
            <div class="category_name">Lands</div>
        </div>
    </a>

    <a href="{% url 'products:product_categories' slug='LIVESTOCK' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'svgs/cow_ct.svg' %}" alt="">
            </div>
            <div class="category_name">Livestock</div>
        </div>
    </a>
    <a href="{% url 'products:product_categories' slug='FRUITS' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'svgs/fruit_ct.svg' %}" alt="">
            </div>
            <div class="category_name">Fruits</div>
        </div>
    </a>
    <a href="{% url 'products:product_categories' slug='OTHER' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image flex a-cent j_cent">
                <img src="{% static 'images/others.png' %}" alt="" style="height:50px;">
            </div>
            <div class="category_name">Others</div>
        </div>
    </a>

    <a href="{% url 'ads:index' %}">
        <div class="category flex_col j_cent a-cent">
            <div class="category_image category_plus flex a-cent j_cent">
                <span class="add_post"></span>
            </div>
            <div class="category_name">Post an Ad</div>
        </div>
    </a>
</section>
<section class="popular_ads">
    <h1>Popular Ads</h1>
    <div class="ads grid">
        {% for ad in sup_ads %}
        <a href="{% url 'products:detail' ad.product.slug %}">
            <div class="ad">
                <div class="image" style="background: none;">
                    <img src="{{ad.image.url}}" alt="" style="height:100%;width:100%;object-fit:cover;">
                </div>
                <div class="ad_dets flex_col" style="color:#000">
                    <p>{{ad.name}}</p>
                    <p class="flex sep">&#8358;{{ad.maximum_price|floatformat:2|intcomma}}
                        <span class="small flex a-cent">
                            <img src="svgs/Icon awesome-angle-left.svg" alt="">

                        </span>
                    </p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</section>
<div class="pagination flex a_cent j_cent" style="margin-top:2rem">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
<script>
    const user_input = $("#user-input")
    const search_icon = $('#search-icon')
    const artists_div = $('.fresh')
    const endpoint = 'https://www.indusmegafarms.com/ads/sponsored_ads/'
    const delay_by_in_ms = 700
    let scheduled_function = false

    let ajax_call = function (endpoint, request_parameters) {
        $.getJSON(endpoint, request_parameters)
            .done(response => {
                // fade out the artists_div, then:
                artists_div.fadeTo('slow', 0).promise().then(() => {
                    // replace the HTML contents
                    artists_div.html(response['html_from_view'])
                    // fade-in the div with new contents
                    artists_div.fadeTo('slow', 1)
                    // stop animating search icon
                    search_icon.removeClass('blink')
                })
            })
    }


    user_input.on('keyup', function () {
        if($(this).val() != ''){
            const request_parameters = {
                q: $(this).val() // value of user_input: the HTML element with ID user-input
            }
    
            // start animating the search icon with the CSS class
            search_icon.addClass('blink')
    
            // if scheduled_function is NOT false, cancel the execution of the function
            if (scheduled_function) {
                clearTimeout(scheduled_function)
            }
    
            // setTimeout returns the ID of the function to be executed
            scheduled_function = setTimeout(ajax_call, delay_by_in_ms, endpoint, request_parameters)
        }
    })

</script>
<script>
document.querySelector('#user-input').addEventListener('keyup',() => {
    if(document.querySelector('#user-input').value == ''){
        document.querySelector('.results').style.display = 'none'
    }
})
</script>
<script src="{% static 'js/popads.js' %}"></script>
<style>
    .ad_categories>a {
        color: #000;
    }

    body,
    html {
        height: 100%;
    }

    .fresh {
        position: absolute;
        width: 100%;
        left: 0;
        bottom: -2px;
    }

    .search_bar {
        position: relative;
    }
</style>
{% endblock content %}
{% block js %}
{% endblock js %}