ads/urls.py
from django.urls import path
from .views import ad_categories_view,AdDetailCreate,ad_category_detail,create_ad,Ads
app_name = 'ads'

urlpatterns = [
    path('',ad_categories_view,name='index'),
    path('<name>',ad_category_detail,name='ad_cat_detail'),
    path('create_ad/',create_ad,name='ad_create'),
    path('ads/',Ads,name='sponsored_ads'),
    path('create-details/',AdDetailCreate.as_view(),name='ad_details_create')
]

blog/urls.py
from django.urls import path
from .views import PostDetailView,PostListView
app_name = 'blog'

urlpatterns = [
    path('',PostListView.as_view(),name='list'),
    path('<slug>',PostDetailView.as_view(),name='detail')
]

indus_mega_farms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from .views import homepage,about,ads_txt
# from ads.views import sponsoredAds

urlpatterns = [
      # path('competitions/',include('i_competitions.urls'))                                              #competitions
      path('oginni/', admin.site.urls),                                                               #admin
      path('',homepage,name='home'),     
      path('ads/',include('ads.urls')),                                                                 #homepage
      path('user/',include('users.urls')),                                                            #users
      path('products/',include('products.urls')),                                                     #products
      path('about/',about,name='about'),                                                              #about us
      url(r"^referrals/", include("pinax.referrals.urls", namespace="pinax_referrals")),              #pinax referrals
      url(r"^account/", include("account.urls")),                                                     #django-user-accounts(for pinax to work smoothly)
      path('paystack',include(('paystack.urls','paystack'),namespace='paystack')),                    #paystack
      path('blog/',include('blog.urls')), 
      path('summernote/', include('django_summernote.urls')),    
      path('management/',include('administration.urls')), 
      path('ads.txt',ads_txt,name='google_ads.txt')       
]

if settings.DEBUG:
      urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

paystack/urls.py
import django

version = django.get_version().split(".")
if int(version[0]) >= 2:
    from django.urls import re_path as url
else:
    from django.conf.urls import url

from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views

urlpatterns = [
    url(
        r"^verify-payment/(?P<order>[\w.@+-]+)/$",
        views.verify_payment,
        name="verify_payment",
    ),
    url(
        r"^failed-verification/(?P<order_id>[\w.@+-]+)/$",
        views.failure_redirect_view,
        name="failed_verification",
    ),
    url(
        r"^successful-verification/(?P<order_id>[\w.@+-]+)/$",
        views.success_redirect_view,
        name="successful_verification",
    ),
    url(
        r"^failed-page/$",
        views.TemplateView.as_view(template_name="paystack/failed-page.html"),
        name="failed_page",
    ),
    url(
        r"^success-page/$",
        views.TemplateView.as_view(template_name="paystack/success-page.html"),
        name="success_page",
    ),
    url(r"^webhook/$", csrf_exempt(views.webhook_view), name="webhook"),
]

products/urls.py
from django.urls import path
from .views import (AddItemToCart,
remove_whole_from_cart,order_final,product_detail,ProductList,
pay_now,add_product_review,ProdCatList,remove_single_item
)


app_name = 'products'

urlpatterns = [
    path('',ProductList.as_view(),name='products'),
    path('product-category/<slug>',ProdCatList.as_view(),name='product_categories'),
    path('add_review',add_product_review,name='add_review'),                                                 #Products
    # path('well',stranger_products,name='stranger'),                                         #products for strangers
    path('<code>/',product_detail,name='detail'),                                  #proposed detail view for products
    path('remove_single/<code>',remove_single_item,name='remove_single'),                         #adding a product to cart
    path('add_to_cart/<code>',AddItemToCart.as_view(),name='add_to_cart'),                         #adding a product to cart
    path('remove_whole_from_cart/<code>',remove_whole_from_cart,name='remove_whole'),       #removing all instances of a product from cart
    path('order_final_summary',order_final,name='order_final'),                             #order summary(cart)
    path('pay_now',pay_now,name='pay_now',)                                                 #pay now
]

users/urls.py
from django.urls import path,re_path,reverse_lazy
from django.shortcuts import redirect
from . import views
from django.contrib.auth.views import (LogoutView,LoginView,PasswordResetView,PasswordResetConfirmView,
PasswordResetDoneView,PasswordResetCompleteView,PasswordChangeView)

app_name = 'users'
urlpatterns = [
    path('category/',views.choice,name='category'),
    path('signup/',views.SignupView.as_view(),name='signup'),
    path('login/',LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('user_home/', views.user_home, name='user_home'),
    path('reg/student',views.StudentReg.as_view(),name='student_reg'),
    path('reg/farmer',views.FarmerReg.as_view(),name='farmer_reg'),
    path('reg/company',views.CompanyReg.as_view(),name='company_reg'),
    path('reset_password',PasswordResetView.as_view(subject_template_name='users/subject_template.txt',email_template_name='users/email_template.html',template_name='users/password_reset.html',success_url = 'password_reset_done'),name='password_reset'),
    path('password_reset_done',PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    re_path('password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',success_url=reverse_lazy('users:password_reset_complete'))
    ,name='password_reset_confirm'),
    path('password_reset_complete',PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    path('change_password',PasswordChangeView.as_view(template_name='users/password_change.html',success_url='login'),name='password_change'),
    path('send_complaint',views.complaint_form,name='send_complaint'),
    # path('farmers_subscribe',views.FarmerSubscribeView.as_view(),name='farmers_subscribe'),
    # path('gold-farmer',views.FarmGoldPlanDetailView.as_view(),name='gold_farmer'),
    # path('silver-farmer',views.FarmSilverPlanDetailView.as_view(),name='silver_farmer'),
    # path('premium-farmer',views.FarmPremiumPlanDetailView.as_view(),name='premium_farmer'),
    # path('company_subscribe',views.CompanySellerPlanView.as_view(),name='company_subscribe'),
    path('harvest-time-ready',views.set_harvest_time,name='set_harvest_time'),
    path('harvest-time-not-ready',views.falsify_harvest_time,name='falsify_harvest_time'),
    ]

templates/about.html
{% extends 'base.html' %} {% load static %} {% block title %}About Indus-Mega
Farms{% endblock %} {%block content %}
<link rel="stylesheet" href="{% static 'css/about.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/presets.css' %}" />
<style>
  .spaced {
    padding-bottom: 0.3rem;
  }
  .concrete {
    display: block;
    font-weight: 500;
  }

  ol{
      padding-left: 1rem;
  }

  @media(max-width:500px){
      .about_container{
          margin-bottom: 200px;
      }
  }
</style>
<div class="about_container" style="width:auto;">
  <h1>About <span style="color:green">Indus-Mega Farms</span></h1>
  <br />
  <span class="white concrete spaced">
    Vision:
  </span>

  <span class="white">
    “Making Agriculture better and attractive in Africa.”
  </span>
  <br />
  <br />
  <span class="white spaced concrete">Missions:</span>
  <ol>
    <li class="white spaced">
      We help farmers sell their products on time by connecting them to a larger
      market.
    </li>
    <li class="white spaced">
      We also produce, aggregate, process, and package agroproducts for sell.
    </li>
    <li class="white spaced">
      We build creative platforms to engage youths in agro-related adventures.
    </li>
  </ol>
  <br />
  <span class="white spaced concrete">Core Values:</span>
  <span class="white">
    Creative, smart, dynamic, pragmatic, innovative and flexible.
  </span>
  <br />
  <br />
  <span class="white concrete spaced">Concept note: </span>
  <span class="white" style="line-height: 150%;">
    "Founded in 2019, Indus-Mega Farms is a gap-bridger between industrial<br />
    markets and farms in Nigeria. We encourage both small and large holder<br />
    farmers to produce better by creating an enabling working evironment with<br />
    zero-waste/funding farming system on ground. We also have built creative<br />
    platforms to engage youths in agro-related adventures."
  </span>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
<script data-ad-client="ca-pub-1372794899198889" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0 user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'svgs/logo.svg' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/presets.css' %}">
    <link rel="stylesheet" href="{% static 'css/loader.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    {% block css %}{% endblock css%}
</head>

<body>
    <div class="backdrop"></div>
    {% include 'nav.html' %}
    {% if messages %}
    {% include 'messages.html' %}
    {% endif %}
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    {% block footer %}
    <div class="footer">
        <div class="footer_wrapper">
            <ul>
                <h4>Information</h4>
                <li><a href="{% url 'about' %}">About Us</a></li>
                <!-- <li><a href="">Policies</a></li> -->
                <li><a href="{% url 'products:order_final' %}">Orders</a></li>
                <!-- <li><a href="">Mission & Vision</a></li> -->
                <!-- <li><a href="">Terms & Conditions</a></li> -->
            </ul>

            <ul>
                <h4>Contact</h4>
                <li><a href="https://www.twitter.com/indusmegafarms">Twitter</a></li>
                <li><a href="https://www.facebook.com/megafarms.indus">Facebook</a></li>
                <li><a href="https://wa.me/2349035136650">Whatsapp</a></li>
                <li><a href="tel:+2349035136650">Mobile</a></li>
            </ul>

            <div class="newsletter">
                <form action="" method="post">
                    <label for="">Sign up for our newsletter:</label>
                    <div class="news_wrapper">
                        <form action="" method="post">
                            {% csrf_token %}
                            <input type="email" name="news_email" id="" placeholder="Email">
                            <input type="submit" value="SUBMIT">
                        </form>
                    </div>
                </form>
            </div>
        </div>
        <div class="copyright">
            <span>&copy;Indus-Mega Farms</span>
        </div>
    </div>
    {% endblock footer %}
</body>
{% block popup %}
{% endblock popup %}
{% block loader %}
<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeee" />
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
            stroke="green" /></svg></div>
<script src="{% static 'js/loader.js' %}"></script>
{% endblock loader %}

<style>
body,html{height:100%;}
</style>


</html>

templates/check_ads.html
<div class="popup">
    <h2>Check out our special products today!</h2>
    <p>Ranging from smoothies to ice-creams and lands..</p>
    <div class="flex" style="justify-content: center;align-items:center;flex-direction: column;">
        <a href="{% url 'ads:sponsored_ads' %}" class="view_them_all">Take a Tour</a>
        <a href="#" class="no_thanks">No, thanks</a>
    </div>
</div>
<style>
    .no_thanks {
        padding: 0.5rem 1rem;
        background: rgb(85, 98, 95);
        color: #fff;
        border-radius: 5px;

    }

    .popup {
        background: rgb(12, 80, 63);
        border-top-left-radius: 20px;
        border-top-right-radius: 20px;
        position: fixed;
        bottom: -400px;
        width: 80%;
        padding: 0.5rem 1rem;
        z-index: 5;
        box-shadow: 0px 3px 30px 60px rgba(204, 204, 204, 0.096);
        box-sizing: border-box;
        transform: translateX(-50%);
        left: 50%;
        transition: 0.4s ease;
        z-index: 16000161;
    }

    @keyframes showedup {
        0% {}

        100% {
            bottom: 0;
        }
    }

    .popup h2 {
        font-size: 2rem;
        text-align: center;
        color: #ccc;
    }

    .view_them_all {
        padding: 0.4rem 1rem;
        background: rgb(37, 190, 73);
        color: #fff;
        margin-top: 1rem;
        border-radius: 5px;
        margin-bottom: 1.5rem;
    }

    .popup p {
        text-align: center;
        color: #ccc;
    }

    .popped {
        animation: showedup 0.4s ease forwards;
        animation-delay: 4s;
    }

    @media(max-width:500px) {
        .popup {
            width: 100vw;
        }

        .popup h2 {
            font-size: 1.4rem;
        }
    }
</style>
<script>
    window.addEventListener('DOMContentLoaded', () => {
        document.querySelector('.popup').classList.add('popped')
    })
    document.querySelector('.no_thanks').addEventListener('click', () => {
        document.querySelector('.popup').classList.remove('popped')

    })
</script>

templates/messages.html
{% if messages %}
{% for message in messages %}
<div class="message">
    <p>{{message}}</p>
</div>
{% endfor %}
{% endif %}

<style>
.message{
    width:100%;
    background:rgb(64, 211, 150);
    color:rgb(255, 255, 255);
    text-align:center;
    position: absolute;
    animation:fade_out 5s ease-in forwards;
    z-index:1000;
}

.message p{
    padding:0.3rem 0;
}

.exit_message{
    position:absolute;
    right:1rem;
}

@keyframes fade_out{
    0%{opacity: 1;}
    50%{opacity:0.3;}
    100%{opacity:0;z-index:-1;display:none;}
}

</style>

templates/nav.html
{% load static %}
<link href="{% static 'css/base.css' %}" rel='stylesheet'/>
<div class="hidden_mobile">
 
    <span onclick="exit_mobile()"></span>
        <ul>{% if not request.user.is_authenticated %}
            <li><a href="{% url 'users:login' %}">Log in</a></li>
            <li><a href="{% url 'users:signup' %}">Sign up</a></li>
            {% endif %}
            <li><a href="{% url 'products:products' %}">Agrowell</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'blog:list' %}">Blog</a></li>
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'users:user_home' %}">Dashboard</a></li>
            <li><a href="{% url 'users:logout' %}">Logout</a></li>
            {% endif %}
        </ul>
    </div>
    <nav class="mobile_nav">
        <img class="toggler" src="{% static 'svgs/nav_toggler.svg' %}" alt="" onclick="bring_mobile()">
        <a href="{% url 'home' %}"><img src="{% static 'svgs/logo.svg' %}" alt=""></a>
        <a href="{% url 'products:order_final' %}"><img src="{% static 'svgs/cart.svg' %}" alt=""></a>
    </nav>
    <nav class="main_nav">
        <a href="{% url 'home' %}">
            <div class="logo">
                <img src="{% static 'svgs/logo.svg' %}" alt="">
                <span>Indus-Mega Farms</span>
            </div>
        </a>
        <ul class="nav_list">
            <li><a href="{% url 'products:order_final' %}" class="nav_a"><img src="{% static 'svgs/cart.svg' %}"
                        alt="cart"></a></li>
            <li><a href="{% url 'products:products' %}" class="nav_a">IMagrowell</a></li>
            <li><a href="{% url 'blog:list' %}" class="nav_a">Blog</a></li>
            <li><a href="{% url 'about' %}" class="nav_a">About</a></li>
            {% if not request.user.is_authenticated %}
            <li class="signup_cta"><a class="nav_signup" href="{% url 'users:login' %}">Log in</a></li>
            {% else %}
            <li><a href="{% url 'users:user_home' %}" class="nav_a">Dashboard</a></li>
            <li><a href="{% url 'users:logout' %}" class="nav_a">Logout</a></li>
            {% endif %}
        </ul>
    </nav>

    <script>
            var mobile_navbar = document.querySelector(".hidden_mobile");
            var backdrop = document.querySelector(".backdrop");
        
            function bring_mobile() {
                mobile_navbar.style.top = 0;
                backdrop.style.display = 'block';
            }
            function exit_mobile() {
                mobile_navbar.style.top = "-350px";
                backdrop.style.display = 'none';
        
            }
        </script>